version: 2

models:
  - name: stg_addresses
    description: "Addresses Table"
    columns:
      - name: address_id
        description: UUID for each unique address on platform
        tests:
          - unique
          - not_null
      - name: address
        description: The first few lines of the address
      - name: zipcode
        description: The zipcode of the address
      - name: state
        description: state this delivery address is based in
      - name: country
        description: country this delivery address is based in
